AllCops:
  TargetRubyVersion: 1.9
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: semantic
  IgnoredMethods:
    - lambda
    - proc
    - it
    - link

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Style/PredicateName:
  NameWhitelist:
    - is_a?
    - has_one
    - has_many
    - has_relationship
